### ISSUE TITLE
ERROR_RATE_LIMITED: You are being rate limited

### ISSUE THREAD

**Issue by hybla0** [nftstorage/nft.storage-tools#8]
I am trying to use the import.js script but i am reporting the following error

🔌 Using endpoint: https://api.nft.storage
  Errored
💖 Total sent: 1
📌 Sending: 12
🔁 Requests/sec: 0.0
✖ Error: pinning bafybeiddaw7khqkuf2hgmrx4h7qf5upjt4d7gz4244svl3uumxg3zybzma: 429: Too Many Requests
Headers: alt-svc,h3=":443"; ma=86400, h3-29=":443"; ma=86400,cf-ray,720f2b97ab4e83bb-MXP,connection,close,content-length,113,content-type,application/json,date,Sat, 25 Jun 2022 16:44:51 GMT,expect-ct,max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct",retry-after,35,server,cloudflare,vary,Accept-Encoding
Body: {
  "ok": false,
  "error": {
    "code": "ERROR_RATE_LIMITED",
    "message": "You are being rate limited"
  }
}
node:internal/process/promises:245
          triggerUncaughtException(err, true /* fromPromise */);
          ^

Error: pinning bafybeiddaw7khqkuf2hgmrx4h7qf5upjt4d7gz4244svl3uumxg3zybzma: 429: Too Many Requests
Headers: alt-svc,h3=":443"; ma=86400, h3-29=":443"; ma=86400,cf-ray,720f2b97ab4e83bb-MXP,connection,close,content-length,113,content-type,application/json,date,Sat, 25 Jun 2022 16:44:51 GMT,expect-ct,max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct",retry-after,35,server,cloudflare,vary,Accept-Encoding
Body: {
  "ok": false,
  "error": {
    "code": "ERROR_RATE_LIMITED",
    "message": "You are being rate limited"
  }
}
    at retry.retries (file:///home/lubuntu/nft.storage-tools/import.js:120:17)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async RetryOperation._fn (file:///home/lubuntu/nft.storage-tools/node_modules/p-retry/index.js:54:13) {
  attemptNumber: 6,
  retriesLeft: 0
}

**Comment by vasco-santos** [comment]
Hello @hybla0 

We have rate limits in place in the API to avoid abuse. You will need to throttle your end per the rate limits specified https://nft.storage/faq/#what-are-the-upload-or-file-size-restrictions-on-nft-storage
